[package]
name = "slog-extra"
version = "0.2.0-alpha1"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Standard slog-rs extensions"
keywords = ["slog", "logging", "log"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-extra"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/extra"
readme = "README.md"

[lib]
path = "lib.rs"

[dependencies]
slog = { git = "https://github.com/slog-rs/slog" }
thread_local = { version = "0.2.6" }
